FROM maven:3.8.6-openjdk-11 as backend-build

WORKDIR /app
COPY yanwai-backend/pom.xml .
COPY yanwai-backend/src ./src
RUN mvn clean package -DskipTests

FROM openjdk:11-jre-slim

WORKDIR /app
COPY --from=backend-build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
