FROM maven:3.9.9-eclipse-temurin-22 AS backend-build

WORKDIR /app
COPY yanwai-backend/pom.xml .
COPY yanwai-backend/src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:22-jre

WORKDIR /app
COPY --from=backend-build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
